export default {
	base: {
		image: {
			width: '100%',
			filter: 'brightness(0.5) sepia(0.2)',
			maxHeight: '90vh',
			h: '90vh',
		},
		overlayText: {
			fontWeight: '500',
			position: 'absolute',
			top: '50%',
			left: '50%',
			transform: 'translate(-50%, -50%)',
			textTransform: 'uppercase',
			width: 'max-content',
		},
		section: {
			paddingY: 12,
		},
		sectionShortWho: {
			paddingY: 20,
			paddingX: { sm: 6, lg: 24 },
			backgroundPosition: '50% 50%',
			background: 'rgb(107, 107, 107)',
			backgroundBlendMode: 'multiply',
			backgroundAttachment: 'fixed',
			backgroundSize: 'cover',
		},
		sectionContent: {
			width: { sm: '100%', lg: '65%' },
			margin: 'auto',
		},
		mapSection: {
			display: 'flex',
			flexDirection: { base: 'column', lg: 'row' },
			bg: '#fff3df',
			alignItems: 'center',
		},
		centeredSection: {
			paddingY: 12,
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
			gap: 20,
		},
		mapInfoWrapper: {
			w: '45vw',
			flex: '1 0 auto',
			height: '100%',
			alignItems: 'center',
			display: 'flex',
			flexDirection: 'column',
			justifyContent: 'center',
			gap: 8,
			textStyle: 'xl',
		},
		mapInfoBox: {
			display: 'flex',
			flexDirection: 'column',
			alignItems: 'center',
		},
		infoTitle: {
			fontWeight: 600,
		},
		textCenter: {
			color: 'white',
			textAlign: 'center',
			paddingX: { sm: 0, lg: 12 },
			textStyle: 'lg',
		},
		buttonContainer: {
			width: 'fit-content',
			margin: 'auto',
			marginTop: 12,
		},
		sectionTitle: {
			textStyle: '3xl',
			textTransform: 'uppercase',
			fontWeight: '500',
			color: 'primary',
			textAlign: 'center',
		},
		threeStyleSection: {
			display: 'grid',
			gridTemplateColumns: '1fr 1fr 1fr',
		},
	},
	slots: [
		'image',
		'overlayText',
		'section',
		'sectionShortWho',
		'sectionContent',
		'mapSection',
		'centeredSection',
		'mapInfoWrapper',
		'mapInfoBox',
		'infoTitle',
		'textCenter',
		'buttonContainer',
		'buttonOutline',
		'buttonOutlinePrimary',
		'sectionTitle',
		'threeStyleSection',
	],
}
