export default {
	main_image: {
		width: '100%',
		height: '250px',
		backgroundColor: 'rgb(107, 107, 107)',
		backgroundBlendMode: 'multiply',
		backgroundPosition: 'center',
		backgroundSize: 'cover',
		filter: 'sepia(0.3)',
	},
	overlayText: {
		position: 'absolute',
		top: '50%',
		left: '50%',
		transform: 'translate(-50%, -50%)',
	},
	section: {
		paddingX: 24,
		paddingY: 24,
		display: 'flex',
		flexDirection: 'column',
		justifyContent: 'space-evenly',
		alignItems: 'center',
		h: 'max(calc(100dvh - var(--header-height)), 550px)',
		position: 'sticky',
		top: 'var(--header-height)',
		bg: 'white',
		borderTop: '1px solid #E5E5E5',
	},
	card_container: {
		display: 'flex',
		columnGap: 24,
		rowGap: 12,
		justifyContent: 'space-evenly',
		alignItems: 'center',
		flexWrap: 'wrap',
		width: '90%',
		height: '60%',
	},
	card: {
		display: 'flex',
		flexDirection: 'column',
		gap: 8,
		justifyContent: 'center',
		alignItems: 'center',
	},
	card_image: {
		width: '15vw',
		height: 'auto',
		objectFit: 'cover',
		maxH: '100px',
		transition: 'all 0.2s',
		transform: 'scale(0.8)',
		display: 'flex',
		justifyContent: 'center',
		alignItems: 'center',

		_active: {
			border: 0,
		},
		_hover: {
			transform: 'scale(1)',
		},
	},
	image: {
		w: '250px',
		height: '150px',
		transition: 'all 0.1s',
	},
}
